# Generated by Django 3.2a1 on 2021-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'stock_stockinfo',
                'managed': False,
            },
        ),
    ]
