# Generated by Django 3.2a1 on 2021-04-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'stock_stockinfo',
            },
        ),
        migrations.CreateModel(
            name='PerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('per', models.PositiveIntegerField(default=10)),
                ('stock_id', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='stock.stockinfo')),
            ],
            options={
                'db_table': 'stock_perinfo',
            },
        ),
    ]
