# Generated by Django 3.2a1 on 2021-04-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='PerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('per', models.PositiveIntegerField(default=10)),
                ('stock_id', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='stock.stockinfo')),
            ],
            options={
                'db_table': 'stock_perinfo',
                'managed': True,
            },
        ),
    ]
