# Generated by Django 3.2a1 on 2021-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210407_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
